# Generated by Django 3.1.3 on 2020-11-15 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Раздел блога')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Пост')),
                ('text', models.TextField(verbose_name='Текст поста')),
                ('short_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Краткое содержание поста')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров поста')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель поста')),
                ('sections', models.ManyToManyField(to='blog.BlogSection', verbose_name='Разделы, в которых опубликован пост')),
            ],
        ),
    ]
