# Generated by Django 3.1.3 on 2020-11-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsection',
            name='slug',
            field=models.SlugField(default='main', verbose_name='Название раздела в ссылке'),
            preserve_default=False,
        ),
    ]
