# Generated by Django 3.1.3 on 2020-11-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201115_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='post', verbose_name='Название поста в ссылке'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название поста'),
        ),
    ]
