# Generated by Django 3.1.3 on 2020-11-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201116_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='Название поста в ссылке'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='Название раздела в ссылке'),
        ),
    ]
