# Generated by Django 3.1.3 on 2020-11-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201116_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название публикации'),
        ),
    ]
